# Generated by Django 3.2.14 on 2023-03-26 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_profiledata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProductCart', '0003_checkout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckOut',
            new_name='CheckOuts',
        ),
    ]
