# Generated by Django 3.2.14 on 2023-03-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20230323_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pincode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
