# Generated by Django 3.1.1 on 2024-05-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_profiledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
